server {
  # Ouve na porta 80
  listen 80;

  # Diretório raiz onde os arquivos do site estão localizados
  root /usr/share/nginx/html;

  # Define o arquivo de entrada principal
  index index.html index.htm;

  location / {
    # Tenta servir o arquivo solicitado diretamente.
    # Se não encontrar, tenta servir um diretório.
    # Se falhar, redireciona para o index.html, onde o Vue Router fará o resto.
    try_files $uri $uri/ /index.html;
  }

  # Configuração opcional para cache de assets
  location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|webp)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
